### ISSUE TITLE
線程必須大於1？

### ISSUE THREAD

**Issue by 687766616e** [needle-wang/sqlmap-wx#1]
線程必須大於`1`？因為我把線程移到`1`，但它會回到`2`........

**Comment by needle-wang** [comment]
你不加这个选项, 就默认是1了.
因为任何程序都是有一个主线程在运行的

**Comment by 687766616e** [comment]
> 因为任何程序都是有一个主线程在运行的

我知道，但.. ok....... ==

**Comment by 687766616e** [comment]
> 線程必須大於1？

我的意思是我不能設置為`1` ^^''

**Comment by needle-wang** [comment]
因为不需要设置为1，不加这个选项就相当于设置为1了。如果非要手动设置为1，可以在生成的语句中手动改成1。

**Comment by 687766616e** [comment]
ok... ^^''
